### ISSUE TITLE
Bot doesn't claim characters when series is multiline

### ISSUE THREAD

**Issue by rkociniewski** [GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024#12]
I noticed bot sometimes doesn't claim character. Here I attach example for Pearl Jam from "JoJo's Bizarre Adventure: Diamond is Unbreakable". Logs:
![Zrzut ekranu 2024-02-12 110411](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/112274712/4177b53d-c90a-4749-8e43-8d40b089483b)

And here in channel:
![Zrzut ekranu 2024-02-12 110446](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/112274712/ad6cfbd2-1ce9-4dda-a6a0-40df67fac912)

I noticed bot doesn't claim, where series name is multiline. You can see on second picture that series is "JoJo's Bizarre Adventure: Diamond
Is Unbreakable", but on logs it's "JoJo's Bizarre Adventure: Diamond". 

How to handle these cases? I tried to  "JoJo's Bizarre Adventure: Diamond Is Unbreakable",  "JoJo's Bizarre Adventure: Diamond" and  "JoJo's Bizarre Adventure: Diamond\nIs Unbreakable", but  bot still doesn't work.

**Comment by GuilleDiazFentanes** [comment]
Yes! You are right, I corrected that issue before but I didn’t put it here, give me some time and today it should be done.
If you want to make it function immediately put the series name until the multi line starts 
In your example it would be until “diamond” skipping the last two words “is unbreakable”

As I see you already tried that, so it may be a typo error I think

**Comment by rkociniewski** [comment]
OK. I changed a series name as per your suggestion. I double checked name, because it could have been a typo.

**Comment by rkociniewski** [comment]
OK, it works. It should be a typo.
