### ISSUE TITLE
Invalid Time Format Problem

### ISSUE THREAD

**Issue by harmanprecious** [GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024#16]
```
C:\mudae>python Bot.py
Traceback (most recent call last):
  File "C:\mudae\Bot.py", line 7, in <module>
    schedule.every().hour.at(timeString).do(simpleRoll)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\schedule\__init__.py", line 521, in at
    raise ScheduleValueError(
schedule.ScheduleValueError: Invalid time format for an hourly job (valid format is (MM)?:SS)

C:\mudae>
```

When i trying to run the bot i'm getting this error.

**Comment by GuilleDiazFentanes** [comment]
Check the time format!!

**Comment by harmanprecious** [comment]
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/87881438/f3dc8608-5016-4728-8d5e-8038d02ec4da)
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/87881438/eda6a2e7-1f21-484f-9704-15c29eaf9119)


Now bot logging anything
My vars like this.

**Comment by GuilleDiazFentanes** [comment]
What file are you executing ? Btw Megumi is Not a kakera type, follow the readme doc ^^

**Comment by harmanprecious** [comment]
Thanks for helping, btw i need Optimized claiming option, when will you share with us?

**Comment by harmanprecious** [comment]
thanks for the reply

**Comment by harmanprecious** [comment]
We need discord server ig.
