### ISSUE TITLE
can't react desired kakera even tho there's one

### ISSUE THREAD

**Issue by Tegarcs142** [GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024#19]
A single kakera reaction can be react like Light one but if theres multiple kakeras like orange, light, yellow and can't react light kakera even tho there desired one because only detect single kakera which in this case orange kakera (i remove orange kakera in desired kakera. Also don't mind custom emoji kakera reaction XD)
![Screenshot 2024-04-03 134404](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/116573935/5ef20995-d39c-4247-b54f-aec40a1ea191)
![Screenshot 2024-04-03 134430](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/116573935/08bffcd8-34f7-425f-9078-a538be1f9d8b)

**Comment by Tegarcs142** [comment]
Finally i fixed myself

**Comment by rahaaatul** [comment]
> Finally i fixed myself

How?

**Comment by Tegarcs142** [comment]
> > Finally i fixed myself
> 
> How?

add this:
cardsKakera2 = (jsonCard[0]['components'][0]['components'][1]['emoji']['name'])
            if cardsKakera2 in Vars.desiredKakeras:
                x -= 1 
                print(kakera+' - '+kakera+' - Trying to react to '+ cardsKakera+ ' of '+ cardName)
                bot.click( jsonCard[0]['author']['id'], channelID =jsonCard[0]['channel_id'], guildID = Vars.serverId, messageID=jsonCard[0]['id'], messageFlags=jsonCard[0]['flags'], data={'component_type': 2, 'custom_id': jsonCard[0]['components'][0]['components'][1]['custom_id']},)

        except IndexError:
            cardsKakera2 = 'null'
        try:
            cardsKakera3 = (jsonCard[0]['components'][0]['components'][2]['emoji']['name'])
            if cardsKakera in Vars.desiredKakeras:
                x -= 1 
                print(kakera+' - '+kakera+' - Trying to react to '+ cardsKakera+ ' of '+ cardName)
                bot.click( jsonCard[0]['author']['id'], channelID =jsonCard[0]['channel_id'], guildID = Vars.serverId, messageID=jsonCard[0]['id'], messageFlags=jsonCard[0]['flags'], data={'component_type': 2, 'custom_id': jsonCard[0]['components'][0]['components'][2]['custom_id']},)

        except IndexError:
            cardsKakera3 = 'null'
