### ISSUE TITLE
Multiple Reacts Per Character

### ISSUE THREAD

**Issue by Pandinoo** [GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024#24]
please add support for multiple reacts appearing. The bot only checks the first react and ignores the potential other 2
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/114646387/f4bd4fe2-4460-4532-afcd-0e2482042c68)

**Comment by Tegarcs142** [comment]
I have fix for this which i discovered myself

**Comment by Tegarcs142** [comment]
> please add support for multiple reacts appearing. The bot only checks the first react and ignores the potential other 2 ![image](https://private-user-images.githubusercontent.com/114646387/326230116-f4bd4fe2-4460-4532-afcd-0e2482042c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjg0NTQsIm5iZiI6MTcyMDM2ODE1NCwicGF0aCI6Ii8xMTQ2NDYzODcvMzI2MjMwMTE2LWY0YmQ0ZmUyLTQ0NjAtNDUzMi1hZmNkLTBlMjQ4MjA0MmM2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxNjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDgxNzliNWExNWU5YTIyZDU4MDlkM2E1MzNkNThhNGM0M2E1OWI3ZjNmMzg2NjM5ZTJjYjkxZjJlMjA2MGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l95bYTD7f2VEX-fKjoBwuAGxgCIgwhhjyp1YGWMxQEY)

Now it's time to update which now fixed multiple kakera reactions
